### ISSUE TITLE
下载文件的时候回调onProgress中的progress参数一直为0

### ISSUE THREAD

**Issue by darkSuperman** [Y0LANDA/NoHttp#184]
作者你好，如题，DownloadListener中的回调onProgress(int what, int progress, long fileCount, long speed) 
progress参数一直是0，而fileCount和speed都有正确返回值,请问作者从哪入手排查问题？或者还是框架本身bug?

**Comment by yanzhenjie** [comment]
![image](https://user-images.githubusercontent.com/13534988/41285731-bcd98b02-6e6f-11e8-8ffc-520ab1571e63.png)
如果用的不是很深入的话，可以了解一下我的新框架Kalle。

**Comment by darkSuperman** [comment]
好的，感谢。
