### ISSUE TITLE
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xbe2642c0: Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by csh159** [Y0LANDA/NoHttp#193]
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xbe2642c0: Failure in SSL library, usually a protocol error
error:1000041a:SSL routines:OPENSSL_internal:TLSV1_ALERT_DECODE_ERROR (external/boringssl/src/ssl/tls_record.c:504 0xda6597e0:0x00000001)

**Comment by yanzhenjie** [comment]
你用的哪个版本？新版修复了这个问题，关于SSL协议版本的问题，你可以看看这篇文章：
[https://blog.csdn.net/yanzhenjie1003/article/details/80202476](https://blog.csdn.net/yanzhenjie1003/article/details/80202476)
