### ISSUE TITLE
NoClassDefFoundError: com.yanzhenjie.nohttp.cookie.DBCookieStore

### ISSUE THREAD

**Issue by Hzh873851987** [Y0LANDA/NoHttp#203]
![tim 20181123100403](https://user-images.githubusercontent.com/27913556/48926259-36eb4d00-ef07-11e8-9a6d-b62aafbb08e6.png)
![Uploading TIM截图20181123100449.png…]()

**Comment by Hzh873851987** [comment]
能看看怎么回事吗
版本是1.1.2

**Comment by yanzhenjie** [comment]
64k问题引起的。

**Comment by Hzh873851987** [comment]
来不及说声谢谢，真快^^
