### ISSUE TITLE
No virtual method setCallWebSocket at okhttp3.ws.WebSocketCall.enqueue

### ISSUE THREAD

**Issue by zhoujunwei** [Y0LANDA/NoHttp#205]
底层请求配置成Okhttp ，报错No virtual method setCallWebSocket at okhttp3.ws.WebSocketCall.enqueue

**Comment by yanzhenjie** [comment]
依赖的各库版本是多少？

**Comment by zhoujunwei** [comment]
"nohttp"          : "com.yanzhenjie.nohttp:nohttp:1.1.11",
"okhttp"          : "com.yanzhenjie.nohttp:okhttp:1.1.11",

**Comment by zhoujunwei** [comment]
跟代码混淆有关吗   代码没做混淆

**Comment by yanzhenjie** [comment]
默认的OkHttp版本是3.11.0，是否有使用更新版本的OkHttp，或者其他库使用了更新版本的OkHtt，或者你是否有强行指定OkHttp版本。单独依赖是没问题，只能这样排查。

**Comment by zhoujunwei** [comment]
目前就是单独依赖，也没有使用或指定其他版本的Okhttp

**Comment by yanzhenjie** [comment]
你的意思是Demo就出这个问题了吗？

**Comment by zhoujunwei** [comment]
Demo 没问题  刚更新的最新版本  切换成了Okhttp ,线上环境没问题，测试环境 一启动就报这个错了

**Comment by yanzhenjie** [comment]
这个错可能是其他库使用了较低版本的OkHttp，本库使用了较高版本的OkHttp，AS会优先使用较高版本的库，导致引用了较低版本OkHttp的库报了错，你得查一下。
