### ISSUE TITLE
问一下网络极端的情况怎么处理的

### ISSUE THREAD

**Issue by csh159** [Y0LANDA/NoHttp#206]
有网咯，但是很慢，一直不返回，一直在请求，就是不会超时！及时移动位置到网络好的地方还是不会返回！

**Comment by yanzhenjie** [comment]
看看有没有报错，没有报错看看多久了没返回，如果在你设置的ReadTime内，那么应该是服务端还未返回数据，如果超过了ReadTime，那么要可能是发生了什么错，得先找到错误。

**Comment by csh159** [comment]
没报错，请求也没返回，就是一直在请求状态中

**Comment by yanzhenjie** [comment]
这不可能的，你要认真排查一下问题，先找到问题才好解决，另外也有可能是你哪里写的有问题，和框架无关的地方，有可能的地方都可以看看。

**Comment by csh159** [comment]
呃呃，好的呢，多排查下，这种情况也只有网络极端的情况才会出现，一般是不会的！
