### ISSUE TITLE
荣耀10手机 饭回 onFailed，response为“”

### ISSUE THREAD

**Issue by zj2050** [Y0LANDA/NoHttp#210]
昨天一个用户的荣耀 10 手机发现异常， 跟踪发现一直回调onFailed， 但回调的 response 为 “”

**Comment by yanzhenjie** [comment]
失败了肯定是空咯，说明是发生了异常，看看发生了什么异常，也可以参考demo如何处理。一直回调failed，说明这个异常一直发生，看具体是什么错误具体解决。
