### ISSUE TITLE
上传请求的数据中包含list list里面是map数据，请问如何上传

### ISSUE THREAD

**Issue by abc8312111** [Y0LANDA/NoHttp#224]
网络请求数据中 需要上传一个数组 数组里面有包含了map键值对，目前的做法是arraylist 嵌套hashMap .但是后台接收到的map为字符串 带双引号的。请问你这个问题如何解决。

**Comment by abc8312111** [comment]
![image](https://user-images.githubusercontent.com/12001505/58616591-9a0fcf00-82f0-11e9-81fb-394324258da7.png)

**Comment by abc8312111** [comment]
param 为map map里面包含一个key值为list<map> list

**Comment by yanzhenjie** [comment]
同一个`key`对应多个`value`：
```java
// 方式一： 
request.add("key", value);
request.add("key", value2);
request.add("key", value3);

// 方式二：
List<Value> list = ...;
list.add(value);
list.add(value2);
list.add(value3);
request.add("key", list);
```

**Comment by abc8312111** [comment]
感谢作者回答我用的是方式二

// 方式二：
List<Value> list = ...;
list.add(value);
list.add(value2);
list.add(value3);
request.add("key", list);
但是我的value为map
List<Map> list = ...;
list.add(map);
list.add(map1);
list.add(map2);
request.add("key", list);
服务器接收到的map类型为带双引号的
正常map  {"name":"123","age":"15"}
实际map "{"name":"123","age":"15"}"

**Comment by yanzhenjie** [comment]
这种嵌套是`Java`的数据结构，`Http`中没有这种方式，`Http`中都是字符串或者流，因此需要转为特定的格式，一般是`JSON`、`XML`或者`Protobuf`。你们服务端期望的是`JSON`，你转为`JSON`就可以了。
