### ISSUE TITLE
上传文件时，调用request.cancle()无法取消上传

### ISSUE THREAD

**Issue by jonyhunter** [Y0LANDA/NoHttp#6]
已测试，确实存在上传无法取消的问题，复现方法很简单，只需在sample项目中的上传代码中增加取消下载功能即可，经测试，在上传过程中，调用Request.cancle()，Request.cancelBySign()，RequestQueue.cancelBySign()以及RequestQueue.cancelAll()均无法停止上传，OnUploadListener中的回调方法依然会被调用，跪求 @Y0LANDA 大神解决。测试系统为Android5.1.1，测试设备为Google Nexus 9。

**Comment by Y0LANDA** [comment]
你好，取消请求是指取消队列中的请求，如果请求已经在执行了是无法取消的，将在新版本中迭代优化这个功能。上传文件是允许取消的，目前NoHttp提供的Binary的默认实现FileBinary有一个cancel(true)方法，调用后可以取消这个文件的上传。
